# Each server has a seperate makefile. This makefile calls the others,
# Satisfying the requirement that "You must deliver the code for the 
#   three servers, as well as a Makefile to build them all, where the 
#   command 'make all' will build all three servers."


all:
	cd server_f && $(MAKE)
	cd server_p && $(MAKE)
	cd server_s && $(MAKE)
