# Generic Makefile where the only lines
# that really need to changes are the sources
# and the executables, with executables the programs
# with main functions

CC=cc  # For C++, change to gcc
CFLAGS=-m32 -g -Wall # Add -g if you want to use the debugger, GDB
LIBS= #-lpthread # Flags for linking, such as math libraries with -lm
SOURCES=a1.h # Usually where you would put objects (e.g. helpers.o) to link into executables
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLES=a1

all: $(SOURCES) $(EXECUTABLES)

clean:
	rm -f $(EXECUTABLES) *.o *~ core

# Want to ensure that executables always recompile, eve
# if there are no changes to dependencies
.PHONY: clean $(EXECUTABLES)

$(EXECUTABLES): $(OBJECTS) 
	$(CC) $(CFLAGS) $(OBJECTS) $@.c -o $@ $(LIBS)

$(OBJECTS): $(SOURCES)
	$(CC) $(CFLAGS) -c $< -o $@


